-- Cole TODO este arquivo no SQL Editor do Supabase e clique em RUN.
create table if not exists public.config (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade unique,
  rec1 numeric default 0, rec2 numeric default 0, dia2 int default 20,
  pct numeric default 20, reserva numeric default 0
);
create table if not exists public.mov (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  data date not null, descricao text, categoria text, tipo text, forma text,
  valor numeric default 0, obs text
);
create table if not exists public.contas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text, categoria text, valor numeric default 0, vencimento date, status text
);
create table if not exists public.cartoes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text, limite numeric default 0, fechamento int, vencimento int, fatura numeric default 0
);
create table if not exists public.dividas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text, saldo numeric default 0, parcela numeric default 0, restantes int default 0
);
create table if not exists public.metas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text, desejado numeric default 0, guardado numeric default 0
);

alter table public.config enable row level security;
alter table public.mov enable row level security;
alter table public.contas enable row level security;
alter table public.cartoes enable row level security;
alter table public.dividas enable row level security;
alter table public.metas enable row level security;

create policy "config_own" on public.config for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "mov_own" on public.mov for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "contas_own" on public.contas for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "cartoes_own" on public.cartoes for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "dividas_own" on public.dividas for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "metas_own" on public.metas for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
