-- Meu Financeiro V69 — pré-vínculo seguro de WhatsApp ao usuário autenticado
create table if not exists public.whatsapp_vinculos (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    nome text not null,
    telefone_e164 text not null unique,
    codigo_vinculo text not null,
    verificado boolean not null default false,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.whatsapp_vinculos enable row level security;

revoke all on table public.whatsapp_vinculos from anon;
grant select, insert, update, delete on table public.whatsapp_vinculos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists whatsapp_vinculos_own on public.whatsapp_vinculos;
create policy whatsapp_vinculos_own
on public.whatsapp_vinculos
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create index if not exists whatsapp_vinculos_user_id_idx
on public.whatsapp_vinculos (user_id);
